all: problem1 problem2 problem5 problem6 problem7 problem8 problem9 problem10

problem1:
	python Problem_1.py
problem2:
	python Problem_2.py
problem5:
	python tries.py
problem6:
	g++ Problem6.cpp -o Problem6 && ./Problem6
problem7:
	python dijkstra2.py
problem8:
	g++ Problem8.cpp -o Problem8 && ./Problem8
problem9:
	python Problem_9.py
problem10:
	g++ Problem10Dyadic.cpp -o Problem10Dyadic && ./Problem10Dyadic
	g++ Problem10Any.cpp -o Problem10Any && ./Problem10Any